services:
  backend:
    build: ./instaclone_back
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://instaclone-mysql:3306/instaclone
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      instaclone-mysql:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build: ./instaclone_front
    ports:
      - 4200:4200
    volumes:
      - ./instaclone_front:/app
    depends_on:
      - backend
    restart: unless-stopped

  instaclone-mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=instaclone
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3307:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
