services:
  backend:
    build: ./instaclone_back
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://$${MYSQL_HOST:instaclone-mysql}:3306/instaclone
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=h0xoA[BkiFI;zK6
    depends_on:
      instaclone-mysql:
        condition: service_healthy
  frontend:
    build: ./instaclone_front
    ports:
      - 4200:4200
    depends_on:
      - backend
  instaclone-mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=h0xoA[BkiFI;zK6
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
