services:
  backend:
    build: ./instaclone_back
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://$${MYSQL_HOST:instaclone-mysql}:3306/instaclone
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      instaclone-mysql:
        condition: service_healthy
  frontend:
    build: ./instaclone_front
    ports:
      - 4200:4200
    volumes:
      - ./instaclone_front:/app
      - /app/node_modules
    depends_on:
      - backend
    command: >
      sh -c "npm install &&
             ng serve --host 0.0.0.0 --poll 2000 --watch"

  instaclone-mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3307:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
